### ISSUE TITLE
Map Tiles are not loaded initially

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-tracking-replay-map-widget#3]
In Application Builder I recognized that the map tiles are not loaded with the result of a grey bar in the map.
Only after resizing the window the map is completely reloaded and visualized.
<img width="1400" alt="Bildschirmfoto 2021-08-10 um 16 43 37" src="https://user-images.githubusercontent.com/12858084/129040127-f235f79f-d6f4-4cf5-83fb-7a5b70f998a9.png">
<img width="1395" alt="Bildschirmfoto 2021-08-10 um 18 16 24" src="https://user-images.githubusercontent.com/12858084/129040137-a12bc60a-ad15-4c50-945b-76b0705db6e6.png">

**Comment by YashPShah-swag** [comment]
Unable to reproduce with latest version.
